// AUTO-GENERATED by scripts/compile-terminology.ts — do not edit by hand.
// Source: src/terminology/terminology.yml
// Run `npm run compile:terminology` to regenerate.

export interface TerminologyEntry {
  id: string;
  canonical_en: string;
  category: string;
  definition: string;
  synonyms: string[];
  deprecated: string[];
  translations: Record<string, string>;
  intent_keywords: Record<string, string[]>;
  ai_notes: string;
  do_not_confuse_with: Array<{ term: string; reason: string }>;
}

export const TERMINOLOGY_INDEX: TerminologyEntry[] = [
  {
    "id": "programme",
    "canonical_en": "Programme",
    "category": "product-hierarchy",
    "definition": "The top-level container that defines an activity type. Holds pricing, payment settings, booking form configuration, and scheduling rules. One Programme can contain multiple Classes.",
    "synonyms": [
      "program"
    ],
    "deprecated": [
      "Course",
      "Open course",
      "One-time course"
    ],
    "translations": {
      "sk": "Program",
      "cz": "Kurz",
      "ro": "Curs",
      "hu": "Kurzus",
      "de": "Programm / Kurs",
      "pl": "Program",
      "it": "Programma",
      "fr": "Programme"
    },
    "intent_keywords": {
      "en": [
        "programme",
        "program",
        "course",
        "activity",
        "class programme"
      ],
      "sk": [
        "program",
        "kurz",
        "aktivita",
        "hodiny"
      ],
      "cz": [
        "kurz",
        "program",
        "aktivita"
      ],
      "ro": [
        "curs",
        "program",
        "activitate"
      ],
      "hu": [
        "kurzus",
        "program",
        "tanfolyam"
      ],
      "de": [
        "Programm",
        "Kurs",
        "Aktivität"
      ]
    },
    "ai_notes": "When domain = widget (client-facing), displayed as 'Class'. Admin always uses 'Programme'. Do not use 'Course' in new English content. 'Kurz' (CZ), 'kurz' (SK), 'curs' (RO), 'kurzus' (HU) are the correct market-language equivalents — they are NOT deprecated in those languages. When a CZ/SK/RO/HU customer says 'kurz/curs/kurzus', they always mean Programme.",
    "do_not_confuse_with": []
  },
  {
    "id": "class",
    "canonical_en": "Class",
    "category": "product-hierarchy",
    "definition": "A scheduled group within a Programme, typically differentiated by day/time, level, or location. Inherits all Programme settings automatically. One Class contains multiple Sessions.",
    "synonyms": [
      "group"
    ],
    "deprecated": [
      "Group",
      "group",
      "Timetable",
      "batch",
      "track"
    ],
    "translations": {
      "sk": "Skupina / Lekcia",
      "cz": "Skupina / Lekce",
      "de": "Gruppe / Kurs",
      "ro": "Grupă",
      "hu": "Csoport",
      "pl": "Grupa",
      "it": "Gruppo",
      "fr": "Classe"
    },
    "intent_keywords": {
      "en": [
        "class",
        "group",
        "timetable",
        "schedule",
        "my class",
        "which group"
      ],
      "sk": [
        "skupina",
        "trieda",
        "hodina",
        "rozvrh",
        "hodiny"
      ],
      "de": [
        "Klasse",
        "Gruppe",
        "Kurs",
        "Stundenplan"
      ],
      "ro": [
        "grupă",
        "grupe"
      ],
      "hu": [
        "csoport"
      ]
    },
    "ai_notes": "'Class' is used at two levels: (1) the subdivision within a Programme (admin view), and (2) the top-level name for a Programme in the client/widget view. Context resolves the ambiguity. In admin, the hierarchy is Programme → Class → Session.",
    "do_not_confuse_with": []
  },
  {
    "id": "session",
    "canonical_en": "Session",
    "category": "product-hierarchy",
    "definition": "A single scheduled meeting within a Class, with a specific date and time. Attendance is recorded at session level. In Zooza, the correct term is always 'Session' — not 'lesson', 'date', 'lekcia', 'lekce', or 'hodina'.",
    "synonyms": [
      "lesson",
      "class session"
    ],
    "deprecated": [
      "slot",
      "appointment",
      "date",
      "time slot"
    ],
    "translations": {
      "sk": "Termín / Hodina / Lekcia",
      "cz": "Termín / Hodina / Lekce",
      "hu": "Óra / Foglalkozás",
      "de": "Termin / Stunde / Einheit",
      "ro": "Lecție",
      "pl": "Termin / Zajęcia",
      "it": "Sessione",
      "fr": "Séance"
    },
    "intent_keywords": {
      "en": [
        "session",
        "lesson",
        "slot",
        "time",
        "date",
        "class date",
        "next session",
        "class time"
      ],
      "sk": [
        "termín",
        "hodina",
        "lekcia",
        "dátum",
        "čas",
        "hodiny",
        "vyučovanie"
      ],
      "cz": [
        "termín",
        "hodina",
        "lekce",
        "datum",
        "čas",
        "výuka",
        "hodiny"
      ],
      "hu": [
        "óra",
        "foglalkozás",
        "időpont",
        "tanóra"
      ],
      "de": [
        "Termin",
        "Stunde",
        "Einheit",
        "Datum"
      ],
      "ro": [
        "lecție",
        "lecții"
      ]
    },
    "ai_notes": "Customers across all markets use 'hodina' (SK/CZ), 'lekcia' (SK), 'lekce' (CZ), 'óra' (HU), 'lesson' (EN) to mean a single scheduled occurrence = Session in Zooza. Always translate these terms to 'Session' when answering or searching KB.",
    "do_not_confuse_with": []
  },
  {
    "id": "pay-as-you-go",
    "canonical_en": "Pay-as-you-go",
    "category": "programme-types",
    "definition": "A flexible programme type where clients book and pay for individual sessions rather than committing to a full term. Often used for drop-in classes.",
    "synonyms": [
      "PAYG",
      "per-session",
      "drop-in"
    ],
    "deprecated": [
      "Open course",
      "Open registration",
      "drop-in",
      "flexible"
    ],
    "translations": {
      "sk": "Platba za termín / Otvorený kurz",
      "cz": "Platba za termín / Otevřená registrace",
      "de": "Pay-as-you-go / Einzelbuchung",
      "pl": "Płatność za termin",
      "ro": "Plata per sesiune",
      "hu": "Alkalmi fizetés",
      "it": "Pagamento a sessione",
      "fr": "Paiement à la séance"
    },
    "intent_keywords": {
      "en": [
        "pay as you go",
        "drop in",
        "single session",
        "flexible",
        "per session",
        "no commitment"
      ],
      "sk": [
        "platba za termín",
        "jednotlivé termíny",
        "bez záväzkov",
        "drop-in"
      ],
      "de": [
        "einzeln",
        "flexibel",
        "ohne Bindung",
        "einzelne Stunde"
      ]
    },
    "ai_notes": "",
    "do_not_confuse_with": []
  },
  {
    "id": "one-off-event",
    "canonical_en": "One-off Event",
    "category": "programme-types",
    "definition": "A single session on a specific date. No repeating schedule. Used for workshops, lectures, consultations, or special events.",
    "synonyms": [
      "workshop",
      "event",
      "one-time event"
    ],
    "deprecated": [
      "One-time course",
      "Registration for one session",
      "single session event",
      "workshop course"
    ],
    "translations": {
      "sk": "Jednorazová udalosť / Jednorazový kurz",
      "cz": "Jednorázová událost / Jednorázový kurz",
      "de": "Einzelveranstaltung / Einmaliger Kurs",
      "pl": "Wydarzenie jednorazowe",
      "ro": "Eveniment unic",
      "hu": "Egyszeri esemény",
      "it": "Evento singolo",
      "fr": "Événement unique"
    },
    "intent_keywords": {
      "en": [
        "one off",
        "one-off",
        "single event",
        "workshop",
        "one time",
        "one session"
      ],
      "sk": [
        "jednorazovo",
        "jednorazový",
        "workshop",
        "prednáška",
        "konzultácia",
        "jednorazový kurz",
        "jednorazový program",
        "jednorazová udalosť",
        "voľné šantenie",
        "voľna hodina",
        "open day",
        "ukážková hodina"
      ],
      "cz": [
        "jednorázově",
        "jednorázový",
        "workshop",
        "přednáška",
        "konzultace",
        "jednorázový kurz"
      ],
      "de": [
        "einmalig",
        "Workshop",
        "Einzeltermin",
        "Veranstaltung"
      ]
    },
    "ai_notes": "",
    "do_not_confuse_with": []
  },
  {
    "id": "membership",
    "canonical_en": "Membership",
    "category": "programme-types",
    "definition": "An ongoing programme with a recurring fixed charge and no fixed end date. Clients are billed on a regular cycle (monthly, quarterly, etc.).",
    "synonyms": [
      "subscription",
      "recurring membership"
    ],
    "deprecated": [],
    "translations": {
      "sk": "Členstvo / Predplatné",
      "cz": "Členství / Předplatné",
      "de": "Mitgliedschaft / Abo",
      "pl": "Członkostwo",
      "ro": "Abonament",
      "hu": "Tagság",
      "it": "Abbonamento",
      "fr": "Abonnement"
    },
    "intent_keywords": {
      "en": [
        "membership",
        "subscription",
        "monthly fee",
        "recurring",
        "ongoing"
      ],
      "sk": [
        "členstvo",
        "predplatné",
        "mesačný poplatok",
        "opakujúca sa platba"
      ],
      "de": [
        "Mitgliedschaft",
        "Abo",
        "monatlich",
        "Dauerauftrag"
      ]
    },
    "ai_notes": "",
    "do_not_confuse_with": []
  },
  {
    "id": "1-to-1-class",
    "canonical_en": "1-to-1 class",
    "category": "programme-types",
    "definition": "A class with a single attendee (individual/private lesson). Admin term for what clients call a Private class.",
    "synonyms": [
      "private class",
      "individual lesson"
    ],
    "deprecated": [
      "Individual class",
      "individual session",
      "private lesson"
    ],
    "translations": {
      "sk": "Individuálna hodina / Súkromná hodina",
      "cz": "Individuální hodina / Soukromá hodina",
      "de": "Einzelstunde / Privatstunde",
      "pl": "Lekcja indywidualna",
      "hu": "Egyéni óra",
      "it": "Lezione individuale",
      "fr": "Cours particulier"
    },
    "intent_keywords": {
      "en": [
        "1 to 1",
        "one to one",
        "private",
        "individual",
        "private class",
        "private lesson"
      ],
      "sk": [
        "individuálna hodina",
        "súkromná hodina",
        "individuálna lekcia",
        "privát"
      ],
      "de": [
        "Einzelstunde",
        "Privatstunde",
        "Einzelunterricht"
      ]
    },
    "ai_notes": "",
    "do_not_confuse_with": []
  },
  {
    "id": "block",
    "canonical_en": "Block",
    "category": "scheduling",
    "definition": "A separately purchasable segment of sessions within a single Class. A Class is divided into Blocks when not all clients attend all sessions — for example, Mondays-only vs. Tuesdays-only vs. both days combined. Each Block has its own price and clients buy only the Block(s) they need.",
    "synonyms": [
      "blok",
      "term"
    ],
    "deprecated": [
      "segment",
      "segmented schedule",
      "schedule segment"
    ],
    "translations": {
      "sk": "Blok",
      "cz": "Blok",
      "de": "Block",
      "hu": "Blokk",
      "ro": "Bloc",
      "pl": "Blok",
      "it": "Blocco",
      "fr": "Bloc"
    },
    "intent_keywords": {
      "en": [
        "block",
        "blocks",
        "block booking",
        "days block",
        "split sessions",
        "buy mondays only",
        "partial attendance",
        "selective sessions"
      ],
      "sk": [
        "blok",
        "bloky",
        "blokové hodiny",
        "blokovanie",
        "čiastočná dochádzka"
      ]
    },
    "ai_notes": "Always use \"Block\" (not \"segment\" or \"segmented schedule\") in any public-facing content, help docs, or client communication. \"Segmented schedule\" and \"segment\" are internal API/spec terms only. When a spec references \"segmented schedule\", translate this to \"Block\" for help content. A Class with blocks is often described as a \"block-based class\".",
    "do_not_confuse_with": [
      {
        "term": "Session",
        "reason": "A Session is a single occurrence (one meeting). A Block is a group of sessions sold together as one purchasable unit within a Class.\n"
      },
      {
        "term": "Payment Plan",
        "reason": "A Payment Plan controls how and when the client pays. A Block controls which sessions the client has access to. They are independent.\n"
      },
      {
        "term": "Make-up session",
        "reason": "Make-up sessions let a client replace a missed session. Blocks define which sessions the client is enrolled in to begin with.\n"
      }
    ]
  },
  {
    "id": "booking",
    "canonical_en": "Booking",
    "category": "bookings",
    "definition": "A client's formal commitment to attend a Class. Creates a payment obligation tied to one specific Class. Managed by admins.",
    "synonyms": [
      "enrolment",
      "registration"
    ],
    "deprecated": [
      "Registration",
      "sign-up",
      "sign up",
      "enrollment"
    ],
    "translations": {
      "sk": "Prihlásenie / Zápis",
      "cz": "Přihlášení / Zápis",
      "de": "Buchung / Anmeldung",
      "pl": "Rezerwacja / Zapis",
      "ro": "Rezervare",
      "hu": "Foglalás",
      "it": "Prenotazione",
      "fr": "Réservation"
    },
    "intent_keywords": {
      "en": [
        "booking",
        "enrolment",
        "enrollment",
        "registration",
        "sign up",
        "sign me up",
        "book a spot"
      ],
      "sk": [
        "prihlásenie",
        "prihláška",
        "zápis",
        "registrácia",
        "prihlásiť"
      ],
      "de": [
        "Buchung",
        "Anmeldung",
        "einschreiben",
        "buchen",
        "anmelden"
      ]
    },
    "ai_notes": "Transfer and Copy both apply to the Booking/Registration entity — not to the Client. If customer says 'move my child', clarify: 'Do you want to move the registration to another class?'",
    "do_not_confuse_with": [
      {
        "term": "Transfer",
        "reason": "Transfer moves a booking to another class; Booking is the enrolment record itself"
      },
      {
        "term": "Copy",
        "reason": "Copy duplicates a booking; the booking is the record being duplicated"
      }
    ]
  },
  {
    "id": "enrolment",
    "canonical_en": "Enrolment",
    "category": "bookings",
    "definition": "The client-facing term for a Booking. Refers to the same record as Booking but used in the client portal and widget context.",
    "synonyms": [
      "booking"
    ],
    "deprecated": [
      "Registration",
      "enrollment"
    ],
    "translations": {
      "sk": "Zápis / Prihlásenie",
      "cz": "Zápis / Přihlášení",
      "de": "Anmeldung / Einschreibung",
      "pl": "Zapis",
      "ro": "Înscriere",
      "hu": "Jelentkezés",
      "it": "Iscrizione",
      "fr": "Inscription"
    },
    "intent_keywords": {
      "en": [
        "enrolment",
        "enrollment",
        "my registration",
        "my booking"
      ],
      "sk": [
        "zápis",
        "prihlásenie"
      ],
      "de": [
        "Anmeldung",
        "Einschreibung"
      ]
    },
    "ai_notes": "Same underlying record as Booking. Use 'Enrolment' in client-facing content and widget documentation. Use 'Booking' in admin/operations documentation.",
    "do_not_confuse_with": []
  },
  {
    "id": "transfer",
    "canonical_en": "Transfer",
    "category": "bookings",
    "definition": "Move a booking/registration from one Class, Group, or Programme to another. The original booking ends and a new booking is created in the target Class.",
    "synonyms": [
      "move",
      "switch"
    ],
    "deprecated": [
      "move booking",
      "switch group",
      "change class",
      "relocate"
    ],
    "translations": {
      "sk": "Presunúť / Prehodiť",
      "cz": "Přesunout",
      "de": "Verschieben / Wechseln",
      "pl": "Przenieść",
      "ro": "Transfer",
      "hu": "Áthelyezés",
      "it": "Trasferimento",
      "fr": "Transfert"
    },
    "intent_keywords": {
      "en": [
        "transfer",
        "move",
        "switch",
        "change group",
        "change class",
        "move to another",
        "switch class"
      ],
      "sk": [
        "presunúť",
        "prehodiť",
        "zmeniť skupinu",
        "presun",
        "premiestiť",
        "iná skupina"
      ],
      "de": [
        "verschieben",
        "wechseln",
        "umbuchen",
        "in andere Gruppe",
        "Gruppenänderung"
      ],
      "pl": [
        "przenieść",
        "zmienić grupę",
        "przeniesienie"
      ],
      "ro": [
        "mută",
        "schimbă grupa",
        "transfer"
      ],
      "hu": [
        "áthelyezni",
        "csoport csere"
      ],
      "it": [
        "spostare",
        "trasferire"
      ],
      "fr": [
        "déplacer",
        "transférer",
        "changer de groupe"
      ]
    },
    "ai_notes": "If customer says: 'move', 'presunúť', 'prehodiť', 'zmeniť skupinu', 'verschieben', 'wechseln', 'przenieść', 'mută', 'áthelyezni', 'spostare', 'déplacer' → treat as Transfer intent. Transfer applies to the Booking, not to the Client entity.",
    "do_not_confuse_with": [
      {
        "term": "Copy",
        "reason": "Transfer moves the booking (original ends); Copy duplicates it (original stays)"
      }
    ]
  },
  {
    "id": "copy",
    "canonical_en": "Copy",
    "category": "bookings",
    "definition": "Duplicate a booking/registration to another Class, Group, or Programme. The original booking remains unchanged. A new booking is created. Payment schedules do not carry over to the copy.",
    "synonyms": [
      "duplicate",
      "clone"
    ],
    "deprecated": [
      "duplicate booking",
      "clone"
    ],
    "translations": {
      "sk": "Kopírovať / Zduplikovať",
      "cz": "Kopírovat / Zduplikovat",
      "de": "Kopieren / Duplizieren",
      "pl": "Skopiować",
      "ro": "Copiere",
      "hu": "Másolás",
      "it": "Copia",
      "fr": "Copier"
    },
    "intent_keywords": {
      "en": [
        "copy",
        "duplicate",
        "clone",
        "also enrol in",
        "add to another class",
        "copy booking"
      ],
      "sk": [
        "kopírovať",
        "duplikovať",
        "zduplikovať",
        "skopírovať",
        "zaradiť aj do"
      ],
      "de": [
        "kopieren",
        "duplizieren",
        "auch einschreiben",
        "in weitere Gruppe"
      ],
      "pl": [
        "skopiować",
        "zduplikować"
      ],
      "ro": [
        "duplică",
        "copie",
        "copiere"
      ],
      "hu": [
        "másolni",
        "duplikálni"
      ],
      "it": [
        "duplicare",
        "copiare"
      ],
      "fr": [
        "copier",
        "dupliquer"
      ]
    },
    "ai_notes": "If customer says: 'copy', 'kopírovať', 'duplikovať', 'zduplikovať', 'kopieren', 'duplizieren', 'skopiować', 'duplică', 'másolni', 'duplicare', 'copier' → treat as Copy intent. Copy applies to the Booking, not to the Client entity. Note: payment schedules and make-up credits do NOT carry over to the copied booking.",
    "do_not_confuse_with": [
      {
        "term": "Transfer",
        "reason": "Copy leaves the original booking in place; Transfer removes it"
      }
    ]
  },
  {
    "id": "network-transfer",
    "canonical_en": "Network transfer",
    "category": "bookings",
    "definition": "Moving one or more client bookings from one company to another company within the same Zooza franchise network. Used when a client switches branches or when a location is closed and clients are migrated to another branch. Available in bulk (multiple bookings at once) via Bulk action → Network transfer.",
    "synonyms": [
      "bulk network transfer"
    ],
    "deprecated": [
      "franchise transfer"
    ],
    "translations": {
      "sk": "Sieťový presun",
      "cz": "Síťový přesun"
    },
    "intent_keywords": {
      "en": [
        "network transfer",
        "transfer to another branch",
        "move client to another location",
        "franchise transfer",
        "bulk transfer"
      ],
      "sk": [
        "sieťový presun",
        "presun na inú pobočku",
        "presun klienta do inej pobočky",
        "franšíza presun"
      ],
      "cz": [
        "síťový přesun",
        "přesun na jinou pobočku"
      ]
    },
    "ai_notes": "Network transfer requires the company to be part of a Zooza franchise network. If the admin cannot see the Network transfer option in Bulk actions, their account is not connected to a network or the feature is not enabled on their plan.",
    "do_not_confuse_with": [
      {
        "term": "Transfer (booking)",
        "reason": "A standard booking transfer moves a client to a different class or programme within the same company. A network transfer moves bookings to a different company in the franchise network.\n"
      }
    ]
  },
  {
    "id": "trial",
    "canonical_en": "Trial",
    "category": "bookings",
    "definition": "A Zooza feature (not just a session type) that makes specific Classes available for prospective clients to try before committing to full enrolment. Trial automates the journey: trial booking → attendance → automated follow-up → enrolment. Status progresses: Trial Started → Trial Won (converted) or Trial Lost. Each Trial has its own price (can be 0), its own registration form, and is published separately via the widget.",
    "synonyms": [
      "trial session",
      "taster"
    ],
    "deprecated": [
      "free trial session",
      "taster session",
      "introductory class"
    ],
    "translations": {
      "sk": "Skúšobná hodina (Zooza Trial)",
      "cz": "Ukázková hodina / Zkušební hodina",
      "hu": "Próbaóra",
      "de": "Probestunde / Schnupperstunde",
      "pl": "Lekcja próbna",
      "ro": "Lecție de probă",
      "it": "Lezione di prova",
      "fr": "Séance d'essai"
    },
    "intent_keywords": {
      "en": [
        "trial",
        "trial session",
        "free session",
        "taster",
        "try out",
        "introductory"
      ],
      "sk": [
        "skúšobná hodina",
        "trial",
        "prvá hodina zadarmo",
        "vyskúšať"
      ],
      "cz": [
        "ukázková hodina",
        "zkušební hodina",
        "trial",
        "zdarma hodina"
      ],
      "hu": [
        "próbaóra",
        "ingyenes óra",
        "próba"
      ],
      "de": [
        "Probestunde",
        "Schnupperstunde",
        "kostenlose Stunde",
        "ausprobieren"
      ]
    },
    "ai_notes": "CRITICAL DISAMBIGUATION: When customer says 'skúšobná hodina', 'zkušební hodina', 'ukázková hodina', 'próbaóra', 'trial', ask: 'Is this set up as a Zooza Trial (with its own registration form and automated follow-up), or did you create a regular session and name it that?' The answer determines entirely different instructions. Zooza Trial = has Trial funnel, own price, own form, automated enrollment flow. Manual session = regular Session with a custom name, no automation.",
    "do_not_confuse_with": [
      {
        "term": "Manually created trial session",
        "reason": "Some admins create a regular Session and name it 'skúšobná hodina' / 'zkušební hodina' without using the Zooza Trial feature at all. These manual sessions have no Trial status tracking, no automated follow-up, and no Trial funnel. When a customer mentions 'skúšobná hodina', always clarify: is it set up as a Zooza Trial, or is it a manually created session with that name?\n"
      }
    ]
  },
  {
    "id": "auto-continuation",
    "canonical_en": "Auto-continuation",
    "category": "bookings",
    "definition": "A Zooza feature that automatically contacts clients before their current Class ends and invites them to re-enrol for the next period. The client receives a personalised link, goes into their Client Profile, and selects which Class they want to continue into. The admin configures how many days before the Class ends the notification is triggered. The client must actively confirm and choose their next Class — no automatic booking is created without client action.",
    "synonyms": [
      "auto-enrolment",
      "automatic re-enrolment",
      "automatic continuation"
    ],
    "deprecated": [],
    "translations": {
      "sk": "Automatické pokračovanie",
      "cz": "Automatické pokračování",
      "hu": "Automatikus folytatás",
      "de": "Automatische Verlängerung / Automatische Fortsetzung",
      "pl": "Automatyczne odnowienie",
      "ro": "Continuare automată",
      "it": "Continuazione automatica",
      "fr": "Continuation automatique"
    },
    "intent_keywords": {
      "en": [
        "auto continuation",
        "automatic continuation",
        "re-enrol",
        "auto enrolment",
        "renew",
        "next term"
      ],
      "sk": [
        "automatické pokračovanie",
        "pokračovanie",
        "obnova",
        "ďalší semester"
      ],
      "cz": [
        "automatické pokračování",
        "pokračování kurzu",
        "obnovení"
      ],
      "hu": [
        "automatikus folytatás",
        "megújítás",
        "következő időszak"
      ],
      "de": [
        "automatische Verlängerung",
        "Verlängerung",
        "nächste Saison",
        "Fortsetzung"
      ]
    },
    "ai_notes": "Auto-continuation is triggered before the Class ends (number of days is configurable). The client receives a personalised link to their Client Profile. From there they choose which Class to continue into. Important: the client MUST actively select a Class — no booking is created automatically. If the customer asks 'does the client get automatically moved?' → answer: No, they get a personalised link and must confirm their choice.",
    "do_not_confuse_with": []
  },
  {
    "id": "registration-status-pending",
    "canonical_en": "Pending (registration status)",
    "category": "bookings",
    "definition": "A registration status indicating the booking has been submitted but is not yet confirmed — typically because payment has not been received or admin approval is required. Pending registrations still hold a capacity spot.",
    "synonyms": [],
    "deprecated": [],
    "translations": {
      "sk": "Čakajúci / Nevybavený",
      "cz": "Čekající / Nevyřízený",
      "de": "Ausstehend",
      "hu": "Függőben"
    },
    "intent_keywords": {
      "en": [
        "pending registration",
        "pending booking",
        "not confirmed",
        "awaiting confirmation",
        "pending status"
      ],
      "sk": [
        "čakajúci",
        "čaká na potvrdenie",
        "nevybavený",
        "čakajúca registrácia",
        "nepotvrdená"
      ],
      "cz": [
        "čekající",
        "nevyřízená registrace",
        "čeká na potvrzení"
      ]
    },
    "ai_notes": "",
    "do_not_confuse_with": []
  },
  {
    "id": "registration-status-awaiting-payment",
    "canonical_en": "Awaiting payment (registration status)",
    "category": "bookings",
    "definition": "A registration status indicating the booking is active but one or more scheduled payments are overdue. The client is still enrolled and attending.",
    "synonyms": [],
    "deprecated": [],
    "translations": {
      "sk": "Čaká na platbu",
      "cz": "Čeká na platbu",
      "de": "Zahlung ausstehend",
      "hu": "Fizetésre vár"
    },
    "intent_keywords": {
      "en": [
        "awaiting payment",
        "payment due",
        "overdue payment",
        "unpaid registration",
        "outstanding payment"
      ],
      "sk": [
        "čaká na platbu",
        "nezaplatené",
        "dlh",
        "čakajúca platba",
        "neuhradené"
      ],
      "cz": [
        "čeká na platbu",
        "nezaplaceno",
        "dluh",
        "čekající platba"
      ]
    },
    "ai_notes": "",
    "do_not_confuse_with": []
  },
  {
    "id": "cancel-vs-delete",
    "canonical_en": "Cancel vs. Archive vs. Delete (Trash)",
    "category": "bookings",
    "definition": "Three distinct actions that customers often confuse by using the word 'vymazať' (SK) or 'smazat' (CZ) for all of them. Cancel = deactivates a registration, record stays visible. Archive = deactivates a programme/class, not deleted. Delete = moves to Trash, recoverable within 30 days. Permanently removed = gone after 30 days or hard-deleted.",
    "synonyms": [],
    "deprecated": [],
    "translations": {
      "sk": "Zrušiť / Archivovať / Vymazať (Koš)",
      "cz": "Zrušit / Archivovat / Smazat (Koš)"
    },
    "intent_keywords": {
      "en": [
        "cancel registration",
        "delete registration",
        "archive programme",
        "trash",
        "restore",
        "undo delete"
      ],
      "sk": [
        "vymazať registráciu",
        "zmazať registráciu",
        "zrušiť registráciu",
        "stornovať",
        "storno",
        "vymazať kurz",
        "vymazať skupinu",
        "koš",
        "obnoviť",
        "vymazané",
        "kde je vymazaná registrácia"
      ],
      "cz": [
        "smazat registraci",
        "zrušit registraci",
        "stornovat",
        "storno",
        "smazat kurz",
        "koš",
        "obnovit"
      ]
    },
    "ai_notes": "",
    "do_not_confuse_with": []
  },
  {
    "id": "cancel-registration-storno",
    "canonical_en": "Cancel (registration)",
    "category": "bookings",
    "definition": "The action of cancelling a registration — marking it as inactive. The record remains in the system and can be reactivated. Different from deletion (Trash).",
    "synonyms": [],
    "deprecated": [],
    "translations": {
      "sk": "Zrušiť registráciu / Storno",
      "cz": "Zrušit registraci / Storno"
    },
    "intent_keywords": {
      "en": [
        "cancel registration",
        "cancel booking",
        "unenrol",
        "remove from class",
        "cancel enrolment"
      ],
      "sk": [
        "zrušiť registráciu",
        "stornovať",
        "storno",
        "odhlásenie",
        "odhlásiť",
        "vyradiť",
        "zrušenie"
      ],
      "cz": [
        "zrušit registraci",
        "stornovat",
        "storno",
        "odhlásení"
      ]
    },
    "ai_notes": "",
    "do_not_confuse_with": []
  },
  {
    "id": "client",
    "canonical_en": "Client",
    "category": "clients",
    "definition": "The person who holds the account, pays, and manages bookings. Identified uniquely by email address. May book on behalf of family members (attendees).",
    "synonyms": [
      "parent",
      "account holder"
    ],
    "deprecated": [
      "parent",
      "customer",
      "account holder"
    ],
    "translations": {
      "sk": "Klient / Zákazník",
      "cz": "Klient / Zákazník",
      "de": "Kunde / Klient",
      "pl": "Klient",
      "ro": "Client",
      "hu": "Ügyfél",
      "it": "Cliente",
      "fr": "Client"
    },
    "intent_keywords": {
      "en": [
        "client",
        "customer",
        "parent",
        "account",
        "my account"
      ],
      "sk": [
        "klient",
        "zákazník",
        "rodič",
        "účet"
      ],
      "de": [
        "Kunde",
        "Klient",
        "Elternteil",
        "Konto"
      ]
    },
    "ai_notes": "",
    "do_not_confuse_with": [
      {
        "term": "Attendee",
        "reason": "Client is the payer/account holder; Attendee is the person who attends sessions (may be a child)"
      }
    ]
  },
  {
    "id": "attendee",
    "canonical_en": "Attendee",
    "category": "clients",
    "definition": "The person who physically attends Sessions. May differ from the Client (e.g., a parent books for their child). For adult learners, Client and Attendee are the same person.",
    "synonyms": [
      "child",
      "participant",
      "student"
    ],
    "deprecated": [
      "child",
      "pupil",
      "student",
      "participant"
    ],
    "translations": {
      "sk": "Účastník / Dieťa",
      "cz": "Účastník / Dítě",
      "de": "Teilnehmer / Kind",
      "pl": "Uczestnik",
      "ro": "Participant",
      "hu": "Résztvevő",
      "it": "Partecipante",
      "fr": "Participant"
    },
    "intent_keywords": {
      "en": [
        "attendee",
        "participant",
        "child",
        "my child",
        "student",
        "pupil"
      ],
      "sk": [
        "účastník",
        "dieťa",
        "žiak",
        "študent"
      ],
      "de": [
        "Teilnehmer",
        "Kind",
        "Schüler"
      ]
    },
    "ai_notes": "",
    "do_not_confuse_with": []
  },
  {
    "id": "instructor",
    "canonical_en": "Instructor",
    "category": "clients",
    "definition": "The person who leads sessions. In Zooza, always referred to as 'Instructor' in English. In SK and CZ always 'lektor' — never 'tréner', 'učiteľ', or 'inštruktor'.",
    "synonyms": [
      "trainer",
      "teacher"
    ],
    "deprecated": [
      "trainer",
      "staff",
      "teacher",
      "lecturer"
    ],
    "translations": {
      "sk": "Lektor",
      "cz": "Lektor",
      "de": "Kursleiter",
      "pl": "Instruktor",
      "ro": "Instructor",
      "hu": "Oktató",
      "it": "Istruttore",
      "fr": "Instructeur"
    },
    "intent_keywords": {},
    "ai_notes": "",
    "do_not_confuse_with": []
  },
  {
    "id": "make-up-session",
    "canonical_en": "Make-up session",
    "category": "attendance",
    "definition": "A replacement session a client can attend after cancelling a scheduled session in advance (before the cancellation deadline). The make-up credit is generated automatically on cancellation. The client selects from available slots in any compatible class that has capacity.",
    "synonyms": [
      "replacement session",
      "catch-up"
    ],
    "deprecated": [
      "Replacement session",
      "replacement lessons",
      "catch-up session",
      "substitute session"
    ],
    "translations": {
      "sk": "Náhradná hodina / Náhrada",
      "cz": "Náhradní hodina / Náhrada",
      "de": "Ersatzstunde / Ersatztermin / Nachholtermin",
      "pl": "Termin zastępczy",
      "ro": "Termen de recuperare",
      "hu": "Pótalkalom",
      "it": "Sessione di recupero",
      "fr": "Séance de rattrapage"
    },
    "intent_keywords": {
      "en": [
        "make-up",
        "makeup",
        "replacement",
        "catch up",
        "missed session",
        "attend another",
        "reschedule",
        "how many hours before make-up",
        "time limit make-up",
        "when can client book make-up"
      ],
      "sk": [
        "náhradná hodina",
        "náhrada",
        "náhradky",
        "náhradka",
        "zmeškané",
        "náhradný termín",
        "preložiť hodinu",
        "limit prihlásenia na náhradnú hodinu",
        "koľko hodín pred termínom",
        "časové obmedzenie náhrady",
        "prihlásenie na náhradnú hodinu",
        "ne ukazuje náhradky",
        "náhradky v blokoch"
      ],
      "cz": [
        "náhradní hodina",
        "náhrada",
        "zmeškané",
        "náhradní lekce",
        "přeložit hodinu",
        "limit přihlášení na náhradní hodinu",
        "kolik hodin před termínem",
        "časové omezení náhrady"
      ],
      "de": [
        "Ersatzstunde",
        "Ersatztermin",
        "Nachholtermin",
        "verpasste Stunde",
        "Nachholen"
      ]
    },
    "ai_notes": "If customer asks about: missed sessions, cancellations, replacement lessons, making up a class, attending instead on another day → treat as make-up session / attendance topic. Only discuss Billable sessions if customer explicitly asks about pricing calculation settings.",
    "do_not_confuse_with": [
      {
        "term": "Transferred make-up session",
        "reason": "Standard make-up session = client picks from available slots within the current class period. Transferred make-up session = unused make-up credits carried over to the next class/period when the current class ends. Configured in Settings → Make-up sessions. In SK/CZ: 'náhrada' = standard make-up; 'prenos náhrady' = transferred make-up (inter-period).\n"
      },
      {
        "term": "Custom replacement lesson",
        "reason": "Custom replacement lesson = client proposes a specific date/time; instructor approves. This is a separate feature from both standard make-up and transferred make-up sessions.\n"
      },
      {
        "term": "Free credits",
        "reason": "Make-up sessions arise from cancellations (attendance logic). Free credits are an allowance granted on a booking (pricing/access logic). Some users incorrectly call make-ups 'free sessions' — clarify if needed.\n"
      },
      {
        "term": "Billable session",
        "reason": "Billable sessions are a pricing calculation setting. Make-up sessions are an attendance management feature. Do not mix these when answering attendance questions.\n"
      }
    ]
  },
  {
    "id": "transferred-make-up-session",
    "canonical_en": "Transferred make-up session",
    "category": "attendance",
    "definition": "Unused make-up credits that are carried over to the next class or billing period when the current class ends. Configured in Settings → Make-up sessions (General Settings). Three modes: transfer up to a set number, expire all at class end, or expire after a fixed number of days. The transferred credits get a new expiration date and can be used in the next period/programme.",
    "synonyms": [
      "make-up carry-over",
      "rollover make-up"
    ],
    "deprecated": [],
    "translations": {
      "sk": "Prenos náhrady / Prenos náhradiek do ďalšieho obdobia",
      "cz": "Přenos náhrady / Přenos náhradních hodin do dalšího období",
      "de": "Übertragene Ersatzstunden / Ersatzstunden-Übertrag"
    },
    "intent_keywords": {
      "en": [
        "transferred make-up",
        "carry over make-up",
        "make-up next period",
        "make-up rollover",
        "unused make-ups",
        "make-up from another company",
        "cross-company make-up"
      ],
      "sk": [
        "prenos náhrady",
        "prenos náhradiek",
        "náhrady do ďalšieho obdobia",
        "nevyužité náhrady",
        "náhradka z inej spoločnosti",
        "prenesená náhradka",
        "náhradka z inej pobočky",
        "náhrady z inej firmy"
      ],
      "cz": [
        "přenos náhrady",
        "přenos náhradních hodin",
        "náhrady do dalšího období",
        "nevyužité náhrady",
        "náhrada z jiné společnosti",
        "přenesená náhrada"
      ]
    },
    "ai_notes": "When a SK/CZ customer says 'prenos náhrady', they almost certainly mean the inter-period credit carry-over feature (transferred make-up sessions), NOT a custom replacement lesson proposal. Check Settings → Make-up sessions → General Settings. Key settings: 'Maximum number of transferred make-up sessions between billing periods' (0 = disabled), 'Number of days to use transferred make-up sessions'.",
    "do_not_confuse_with": [
      {
        "term": "Make-up session",
        "reason": "Standard make-up session = client picks a slot within the current class period. Transferred make-up session = unused credits carried into the NEXT period/class after the current class ends. Both are configured in Settings → Make-up sessions.\n"
      },
      {
        "term": "Custom replacement lesson",
        "reason": "Custom replacement = client proposes a specific date/time, instructor approves. Transferred make-up = automatic carry-over of unused credits between billing periods.\n"
      }
    ]
  },
  {
    "id": "custom-replacement-lesson",
    "canonical_en": "Custom replacement lesson",
    "category": "attendance",
    "definition": "A feature that lets a client propose a specific date and time for a replacement session to their instructor. The instructor checks availability and approves or declines. If approved, the replacement session is created automatically. Designed for individual/specialist sessions (piano, personal training, counselling) where booking into another group is not practical.",
    "synonyms": [
      "custom replacement",
      "proposed replacement"
    ],
    "deprecated": [],
    "translations": {
      "sk": "Vlastná náhradná hodina / Náhrada na vlastný termín",
      "cz": "Vlastní náhradní hodina / Náhrada na vlastní termín",
      "de": "Individuelle Ersatzstunde / Eigener Ersatztermin"
    },
    "intent_keywords": {
      "en": [
        "custom replacement",
        "propose replacement",
        "request replacement time",
        "individual replacement",
        "own date replacement"
      ],
      "sk": [
        "vlastná náhrada",
        "navrhnúť termín náhrady",
        "dohodnutý termín",
        "náhrada na vlastný termín"
      ],
      "cz": [
        "vlastní náhrada",
        "navrhnout termín náhrady",
        "dohodnutý termín",
        "náhrada na vlastní termín"
      ],
      "de": [
        "individuelle Ersatzstunde",
        "eigener Ersatztermin",
        "Termin vorschlagen"
      ]
    },
    "ai_notes": "Custom replacement lessons require the instructor-approval workflow. See: content/guides/custom-replacement-lessons.md",
    "do_not_confuse_with": [
      {
        "term": "Transferred make-up session",
        "reason": "Custom replacement = client proposes new date/time, instructor approves. Transferred make-up = automatic carry-over of unused credits between billing periods.\n"
      },
      {
        "term": "Make-up session",
        "reason": "Standard make-up = client picks from existing available slots in compatible classes. Custom replacement = client proposes a new date/time for instructor approval.\n"
      }
    ]
  },
  {
    "id": "free-credits",
    "canonical_en": "Free credits",
    "category": "attendance",
    "definition": "An allowance granted to a specific booking that lets the client attend extra sessions without paying. Managed as credits on the booking record. Different from make-up credits generated by cancellations.",
    "synonyms": [
      "free session allowance",
      "complimentary credits"
    ],
    "deprecated": [
      "free sessions",
      "voľné termíny",
      "complimentary sessions"
    ],
    "translations": {
      "sk": "Voľné termíny / Kredity zadarmo",
      "cz": "Volné termíny / Kredity zdarma",
      "de": "Freistunden / Gratisguthaben"
    },
    "intent_keywords": {
      "en": [
        "free sessions",
        "free credits",
        "complimentary",
        "extra sessions",
        "sessions included"
      ],
      "sk": [
        "voľné termíny",
        "zadarmo",
        "zadarmo termíny",
        "kredity zadarmo"
      ],
      "de": [
        "Freistunden",
        "gratis",
        "kostenlose Stunden",
        "Gutschrift"
      ]
    },
    "ai_notes": "",
    "do_not_confuse_with": [
      {
        "term": "Make-up session",
        "reason": "Free credits = granted allowance on a booking (pricing/access). Make-up sessions = earned by cancelling before deadline (attendance). Users often confuse the two.\n"
      },
      {
        "term": "Billable session",
        "reason": "Billable sessions are a pricing setting, not an attendance benefit."
      }
    ]
  },
  {
    "id": "billable-session",
    "canonical_en": "Billable session",
    "category": "attendance",
    "definition": "A session that counts towards the total used for price calculation in Programme/Class settings. Marking a session as non-billable (e.g. public holidays) excludes it from the price formula. This is a pricing tool only.",
    "synonyms": [
      "billable date",
      "chargeable session"
    ],
    "deprecated": [],
    "translations": {
      "sk": "Spoplatnený termín",
      "cz": "Zpoplatněný termín",
      "de": "Abrechenbare Stunde"
    },
    "intent_keywords": {},
    "ai_notes": "Only discuss billable sessions when a customer explicitly asks about the billable session feature or pricing calculation. Never mention billable sessions in response to attendance, cancellation, or make-up questions.",
    "do_not_confuse_with": [
      {
        "term": "Make-up session",
        "reason": "Billable sessions affect pricing only. Make-up sessions are attendance management."
      },
      {
        "term": "Free credits",
        "reason": "Billable sessions are a price calculation tool. Free credits are an attendance benefit."
      }
    ]
  },
  {
    "id": "payment-plan",
    "canonical_en": "Payment Plan",
    "category": "payments",
    "definition": "The configuration that defines when and how often a client is billed for a booking. Can be one-time, monthly, quarterly, by-block, etc.",
    "synonyms": [
      "payment schedule"
    ],
    "deprecated": [
      "Payment schedule",
      "Scheduled payments",
      "invoice profile",
      "payment template",
      "billing frequency",
      "recurring payments"
    ],
    "translations": {
      "sk": "Platobný plán",
      "cz": "Platební plán",
      "de": "Zahlungsplan / Zahlungsrhythmus",
      "pl": "Plan płatności",
      "ro": "Plan de plată",
      "hu": "Fizetési terv",
      "it": "Piano di pagamento",
      "fr": "Plan de paiement"
    },
    "intent_keywords": {
      "en": [
        "payment plan",
        "payment schedule",
        "how to pay",
        "billing",
        "instalments",
        "when billed",
        "recurring payments",
        "pause payments",
        "unschedule payments",
        "cancel recurring",
        "stop payments",
        "defer payment",
        "postpone payment"
      ],
      "sk": [
        "platobný plán",
        "spôsob platby",
        "platba",
        "fakturácia",
        "splátky"
      ],
      "de": [
        "Zahlungsplan",
        "Zahlungsrhythmus",
        "Ratenzahlung",
        "wann zahlen"
      ]
    },
    "ai_notes": "",
    "do_not_confuse_with": []
  },
  {
    "id": "aliquot",
    "canonical_en": "Aliquot",
    "category": "payments",
    "definition": "A pro-rata pricing method for clients who join a class or programme after it has started. The first payment is automatically calculated based on the number of remaining sessions (or days) in the billing period rather than the full period price. Configured under Programme → Price and Payment → Advanced settings → Aliquot price calculation.",
    "synonyms": [
      "pro-rata",
      "prorated payment",
      "aliquot billing"
    ],
    "deprecated": [],
    "translations": {
      "sk": "Alikvóta / alikvótna suma",
      "cz": "Alikvota",
      "de": "Anteilige Zahlung",
      "pl": "Płatność proporcjonalna"
    },
    "intent_keywords": {
      "en": [
        "aliquot",
        "pro-rata",
        "prorated",
        "partial first payment",
        "join mid-term",
        "late joiner price",
        "remaining sessions price"
      ],
      "sk": [
        "alikvóta",
        "alikvótna suma",
        "výpočet alikvóty",
        "pomerná platba",
        "neskoré prihlásenie cena",
        "čiastočná platba"
      ],
      "cz": [
        "alikvota",
        "poměrná platba",
        "přihlášení v průběhu",
        "krácená platba"
      ]
    },
    "ai_notes": "When a customer asks why the first payment is lower or asks about pricing for mid-term joiners, this is the aliquot feature. Covered in content/faq/payments-and-billing-faq.md and content/guides/late-bookings.md.",
    "do_not_confuse_with": []
  },
  {
    "id": "reference-number",
    "canonical_en": "Reference number",
    "category": "payments",
    "definition": "A unique identifier included with bank transfer payments to allow automatic matching of incoming payments to the correct client booking.",
    "synonyms": [
      "variable symbol",
      "payment reference"
    ],
    "deprecated": [
      "Variable symbol",
      "variabilný symbol",
      "VS"
    ],
    "translations": {
      "sk": "Variabilný symbol / Referenčné číslo",
      "cz": "Variabilní symbol / Referenční číslo",
      "de": "Verwendungszweck / Referenznummer",
      "pl": "Numer referencyjny",
      "ro": "Număr de referință",
      "hu": "Hivatkozási szám",
      "it": "Numero di riferimento",
      "fr": "Numéro de référence"
    },
    "intent_keywords": {
      "en": [
        "reference number",
        "payment reference",
        "bank transfer reference"
      ],
      "sk": [
        "variabilný symbol",
        "referenčné číslo",
        "VS",
        "prevod"
      ],
      "de": [
        "Verwendungszweck",
        "Referenznummer",
        "Überweisung"
      ]
    },
    "ai_notes": "",
    "do_not_confuse_with": []
  },
  {
    "id": "inbound-payment",
    "canonical_en": "Inbound payment",
    "category": "payments",
    "definition": "A bank transfer received from a client that the system automatically attempts to match (pair) to the corresponding booking. Inbound payments are detected via GoCardless bank account data, bank email notifications, or CSV import. Once matched, the payment is recorded on the booking.",
    "synonyms": [
      "incoming bank transfer",
      "paired payment"
    ],
    "deprecated": [
      "incoming payment",
      "bank transfer matching"
    ],
    "translations": {
      "sk": "Prichádzajúca platba / Platba prevodom",
      "cz": "Příchozí platba",
      "de": "Eingehende Zahlung",
      "pl": "Przychodzące płatności"
    },
    "intent_keywords": {
      "en": [
        "inbound payment",
        "bank transfer",
        "payment not matched",
        "payment pairing",
        "unmatched payment",
        "manual pairing",
        "standing order",
        "variable symbol",
        "reference number payment"
      ],
      "sk": [
        "prichádzajúca platba",
        "prevod",
        "platba nespárovaná",
        "spárovanie platby",
        "platba nebola priradená",
        "párovanie platieb",
        "variabilný symbol",
        "VS",
        "trvaly príkaz",
        "stály príkaz",
        "platba sa nespárovala",
        "platba nenašla registráciu"
      ],
      "cz": [
        "příchozí platba",
        "převod",
        "nespárovaná platba",
        "párování platby",
        "variabilní symbol",
        "trvalý příkaz",
        "platba se nespárovala"
      ]
    },
    "ai_notes": "When a user says \"payment not paired\", \"payment stuck\", or \"payment not showing\", they mean an inbound payment that landed in manual review (status: new). Guide them to Sales & Payments → Inbound Payments and pair manually. When they say \"payment not arriving\", check GoCardless consent expiry first.",
    "do_not_confuse_with": [
      {
        "term": "GoCardless direct debit",
        "reason": "GoCardless serves two separate roles in Zooza. As a direct debit gateway, it collects payments directly from clients' bank accounts (mandate-based). As a bank account data provider (open banking), it reads transactions arriving in the company's own bank account. Inbound payments use the bank data role — the client still pays by normal bank transfer; GoCardless only detects it.\n"
      },
      {
        "term": "Payment plan / scheduled payment",
        "reason": "A scheduled payment is a debt entry created by Zooza's payment schedule. An inbound payment is the actual money arriving from the bank. They are matched together by the pairing process.\n"
      }
    ]
  },
  {
    "id": "entry-pass",
    "canonical_en": "Entry pass",
    "category": "payments",
    "definition": "A prepaid bundle that grants access to a set number of sessions (visits-based) or a credit amount (money-based). Used primarily with Pay-as-you-go programmes.",
    "synonyms": [
      "credit pass",
      "visit pass"
    ],
    "deprecated": [
      "credit pass",
      "visit pass",
      "prepaid sessions",
      "pass"
    ],
    "translations": {
      "sk": "Vstupová permanentka / Kredit",
      "cz": "Vstupová permanentka / Kredit",
      "de": "Eintrittskarte / Guthaben / Pass",
      "pl": "Karnet wejściowy",
      "ro": "Card de intrare",
      "hu": "Belépőjegy",
      "it": "Tessera d'ingresso",
      "fr": "Carte d'entrée"
    },
    "intent_keywords": {
      "en": [
        "entry pass",
        "pass",
        "credit",
        "prepaid",
        "bundle",
        "10 sessions",
        "top up"
      ],
      "sk": [
        "pass",
        "kredit",
        "predplatené hodiny",
        "vstupová karta",
        "nabiť kredit",
        "permanentka",
        "permanentky"
      ],
      "de": [
        "Eintrittskarte",
        "Guthaben",
        "Prepaid",
        "Paket",
        "aufladen"
      ]
    },
    "ai_notes": "",
    "do_not_confuse_with": [
      {
        "term": "Credit (overpayment)",
        "reason": "Credit (overpayment) = arises automatically when a client pays more than owed. Entry pass credit = a prepaid bundle the client purchases intentionally. Both show as 'credit' in different contexts — clarify which type before advising.\n"
      }
    ]
  },
  {
    "id": "credit-balance",
    "canonical_en": "Credit",
    "category": "payments",
    "definition": "A positive balance on a client's booking that arises when they have paid more than the total amount owed (overpayment). The credit is displayed on the booking's payment tile and can be applied to future invoices or refunded. Distinct from Entry pass credits (prepaid session bundles).",
    "synonyms": [
      "overpayment credit",
      "payment credit"
    ],
    "deprecated": [
      "preplatok"
    ],
    "translations": {
      "sk": "Preplatok / Kredit z preplatku",
      "cz": "Přeplatek / Kredit z přeplatku",
      "de": "Guthaben / Überzahlung",
      "pl": "Nadpłata",
      "hu": "Túlfizetés"
    },
    "intent_keywords": {
      "en": [
        "credit",
        "overpayment",
        "paid too much",
        "credit on account",
        "apply credit",
        "negative balance",
        "client credit",
        "credit from payment"
      ],
      "sk": [
        "preplatok",
        "preplatok na konte",
        "doplatok",
        "zaplatil viac",
        "kredit z preplatku",
        "záporný zostatok",
        "klient preplácal"
      ],
      "cz": [
        "přeplatek",
        "zaplatil více",
        "kredit z přeplatku",
        "záporný zůstatek"
      ],
      "de": [
        "Guthaben",
        "Überzahlung",
        "zu viel bezahlt",
        "Gutschrift"
      ]
    },
    "ai_notes": "When a SK/CZ customer says 'preplatok' or 'zaplatil viac', they mean the client has overpaid and there is a credit sitting on their booking. This credit can be: (a) applied to a future invoice, or (b) refunded manually. Guide admin to: Booking → Payments → Payment tile → Credit. Do NOT confuse with Entry pass credit balance (entirely different feature).",
    "do_not_confuse_with": [
      {
        "term": "Entry pass",
        "reason": "Credit (overpayment) = arises automatically when a client pays more than owed. Entry pass credit = a prepaid bundle the client purchases intentionally. Both show as 'credit' in different contexts — clarify which type before advising.\n"
      },
      {
        "term": "Down payment",
        "reason": "Down payment = money collected upfront as part of an agreed payment plan. Credit = excess money paid beyond what was owed.\n"
      }
    ]
  },
  {
    "id": "down-payment",
    "canonical_en": "Down payment",
    "category": "payments",
    "definition": "An upfront partial payment collected at the time of booking as a commitment fee. The remaining balance is charged later according to the payment plan. Can be a fixed amount or a percentage of the total price. Commonly used for camps, retreats, and multi-day events.",
    "synonyms": [
      "deposit",
      "advance payment"
    ],
    "deprecated": [
      "deposit"
    ],
    "translations": {
      "sk": "Záloha / Preddavok",
      "cz": "Záloha / Záloha na kurz",
      "de": "Anzahlung / Vorauszahlung",
      "pl": "Zaliczka",
      "ro": "Avans",
      "hu": "Előleg",
      "it": "Acconto",
      "fr": "Acompte"
    },
    "intent_keywords": {
      "en": [
        "down payment",
        "deposit",
        "advance payment",
        "partial payment upfront",
        "pay deposit",
        "book with deposit",
        "commitment fee"
      ],
      "sk": [
        "záloha",
        "preddavok",
        "záloha na kurz",
        "zložiť zálohu",
        "platba vopred"
      ],
      "cz": [
        "záloha",
        "záloha na kurz",
        "záloha při přihlášení",
        "platba předem"
      ],
      "de": [
        "Anzahlung",
        "Vorauszahlung",
        "Reservierungsgebühr"
      ]
    },
    "ai_notes": "When a SK/CZ customer says 'záloha', they always mean the down payment (initial commitment fee), not a subscription or ongoing payment. Down payment is set per Programme; guide admin to Programme → Price & Payment. See: content/guides/price-and-payment-setup.md",
    "do_not_confuse_with": [
      {
        "term": "Payment Plan",
        "reason": "Down payment = the initial partial payment at booking time. Payment Plan = the recurring schedule for the remaining balance. They are configured together in Programme → Price & Payment Setup.\n"
      }
    ]
  },
  {
    "id": "term-payment",
    "canonical_en": "Term Payment",
    "category": "payments",
    "definition": "A payment covering a specific term or billing period, as opposed to a single session or full-programme upfront payment.",
    "synonyms": [],
    "deprecated": [
      "Course fee",
      "Programme fee"
    ],
    "translations": {
      "sk": "Platba za semester / Termínová platba",
      "cz": "Platba za semestr",
      "de": "Kursbeitrag / Semesterbeitrag"
    },
    "intent_keywords": {},
    "ai_notes": "",
    "do_not_confuse_with": []
  },
  {
    "id": "invoice-buyer",
    "canonical_en": "Invoice buyer",
    "category": "payments",
    "definition": "The entity (person or company) recorded as the recipient/orderer on an invoice. May differ from the client who registered — for example, a parent registers a child but invoices must be in the parent's company name. Zooza stores invoice buyer profiles per client and reuses them across bookings.",
    "synonyms": [
      "buyer",
      "billing contact"
    ],
    "deprecated": [
      "orderer",
      "invoice orderer"
    ],
    "translations": {
      "sk": "Odberateľ na faktúre",
      "cz": "Odběratel na faktuře"
    },
    "intent_keywords": {
      "en": [
        "invoice buyer",
        "invoice name",
        "wrong name on invoice",
        "company on invoice",
        "change invoice details",
        "buyer details",
        "orderer"
      ],
      "sk": [
        "odberateľ na faktúre",
        "firma na faktúre",
        "zmeniť faktúru",
        "meno na faktúre",
        "fakturačné údaje"
      ],
      "cz": [
        "odběratel na faktuře",
        "firma na faktuře",
        "změnit fakturu",
        "fakturační údaje"
      ]
    },
    "ai_notes": "If a user says \"wrong name on invoice\" or \"need company invoice\", they need to edit the invoice buyer profile on the client record and regenerate the invoice. Regeneration is supported for Faktury Online and Xero only. For other engines, the user must correct the invoice manually in their accounting software.",
    "do_not_confuse_with": [
      {
        "term": "Invoice profile (billing profile)",
        "reason": "The invoice profile (billing profile) is the supplier side — your company's name, address, and IBAN that appear as the issuer on every invoice. The invoice buyer is the recipient side — the client's billing details.\n"
      }
    ]
  },
  {
    "id": "venue",
    "canonical_en": "Venue",
    "category": "settings",
    "definition": "A physical location where Sessions take place. Assigned at Class level.",
    "synonyms": [
      "location"
    ],
    "deprecated": [
      "Place",
      "Location",
      "place",
      "location"
    ],
    "translations": {
      "sk": "Miesto / Sála / Prevádzka",
      "cz": "Místo / Sál / Provozovna",
      "de": "Standort / Ort / Halle",
      "pl": "Miejsce",
      "ro": "Loc",
      "hu": "Helyszín",
      "it": "Luogo",
      "fr": "Lieu"
    },
    "intent_keywords": {
      "en": [
        "venue",
        "location",
        "place",
        "address",
        "where",
        "room",
        "hall"
      ],
      "sk": [
        "miesto",
        "adresa",
        "kde",
        "sála",
        "miestnosť"
      ],
      "de": [
        "Standort",
        "Ort",
        "Adresse",
        "Halle",
        "wo"
      ]
    },
    "ai_notes": "",
    "do_not_confuse_with": []
  },
  {
    "id": "retention",
    "canonical_en": "Retention",
    "category": "client-management",
    "definition": "A Zooza feature that sends a re-engagement link to clients whose trial was lost or whose booking was cancelled, giving them a time-limited opportunity to return. The admin configures how many days the re-engagement link remains active and can add a personalised note. Configurable per programme under Programme → Settings → Retention.",
    "synonyms": [
      "re-engagement",
      "churn prevention",
      "win-back"
    ],
    "deprecated": [
      "re-engagement"
    ],
    "translations": {
      "sk": "Retencia",
      "cz": "Retence",
      "de": "Kundenbindung",
      "pl": "Retencja",
      "ro": "Retenție",
      "hu": "Visszatartás"
    },
    "intent_keywords": {
      "en": [
        "retention",
        "re-engagement",
        "win back client",
        "bring client back",
        "trial lost follow-up",
        "lapsed client",
        "churn prevention",
        "re-engage"
      ],
      "sk": [
        "retencia",
        "retencia klienta",
        "vrátiť klienta",
        "stratený klient",
        "osloviť stratených",
        "retencný link",
        "retenčný odkaz"
      ],
      "cz": [
        "retence",
        "retence klienta",
        "vrátit klienta",
        "ztracený klient",
        "retenční odkaz"
      ]
    },
    "ai_notes": "Retention is accessed via Programme → Settings → Retention (not via the Loyalty program). It is distinct from the Loyalty Program (which rewards active clients). Retention targets clients who already left or never converted (Trial Lost / Cancelled). The admin sets the number of days the retention link is accessible and an optional note. This is a configurable-days feature — the default was 30 days, but admins can change it per programme.",
    "do_not_confuse_with": [
      {
        "term": "Loyalty Program",
        "reason": "Retention targets clients who already left (Trial Lost / Cancelled). Loyalty Program rewards clients who are still active.\n"
      }
    ]
  },
  {
    "id": "feedback",
    "canonical_en": "Feedback",
    "category": "communication",
    "definition": "Structured feedback collected from clients after sessions or at the end of a programme. Accessible in reports.",
    "synonyms": [
      "review",
      "rating"
    ],
    "deprecated": [
      "Course feedback",
      "review",
      "survey"
    ],
    "translations": {
      "sk": "Spätná väzba / Hodnotenie",
      "cz": "Zpětná vazba / Hodnocení",
      "de": "Feedback / Bewertung",
      "pl": "Opinie",
      "ro": "Feedback",
      "hu": "Visszajelzés",
      "it": "Feedback",
      "fr": "Feedback"
    },
    "intent_keywords": {
      "en": [
        "feedback",
        "review",
        "rating",
        "survey",
        "client feedback"
      ],
      "sk": [
        "spätná väzba",
        "hodnotenie",
        "recenzia"
      ],
      "de": [
        "Feedback",
        "Bewertung",
        "Rückmeldung"
      ]
    },
    "ai_notes": "",
    "do_not_confuse_with": []
  },
  {
    "id": "widget",
    "canonical_en": "Widget",
    "category": "platform",
    "definition": "An embeddable booking interface placed on the activity provider's website. Widgets are the client-facing domain. Everything displayed in a widget uses client-facing terminology.",
    "synonyms": [
      "booking widget",
      "booking form",
      "calendar widget",
      "client portal widget"
    ],
    "deprecated": [],
    "translations": {
      "sk": "Widget / Rezervačný formulár",
      "cz": "Widget / Rezervační formulář",
      "de": "Widget / Buchungsformular"
    },
    "intent_keywords": {
      "en": [
        "widget",
        "booking form",
        "website form",
        "embed",
        "booking button"
      ],
      "sk": [
        "widget",
        "rezervačný formulár",
        "na webe",
        "formulár"
      ],
      "de": [
        "Widget",
        "Buchungsformular",
        "einbetten",
        "Webseite"
      ]
    },
    "ai_notes": "When domain = widget, all terminology flips to client-facing variants: Programme → Class, Booking → Enrolment, etc.",
    "do_not_confuse_with": []
  },
  {
    "id": "client-profile",
    "canonical_en": "Client Profile",
    "category": "platform",
    "definition": "The self-service dashboard where clients manage their bookings, payments, and family members. Accessed via email link (no password required).",
    "synonyms": [
      "client portal",
      "parent portal"
    ],
    "deprecated": [
      "parent portal",
      "customer portal",
      "client portal"
    ],
    "translations": {
      "sk": "Profil klienta / Klientske konto",
      "cz": "Profil klienta / Klientský účet",
      "de": "Kundenprofil / Kundenbereich"
    },
    "intent_keywords": {
      "en": [
        "client profile",
        "my profile",
        "portal",
        "my account",
        "login",
        "access my account"
      ],
      "sk": [
        "profil",
        "môj profil",
        "klientske konto",
        "prihlásenie",
        "prístup"
      ],
      "de": [
        "Profil",
        "mein Profil",
        "Kundenbereich",
        "mein Konto",
        "Anmeldung"
      ]
    },
    "ai_notes": "",
    "do_not_confuse_with": []
  },
  {
    "id": "loyalty-program",
    "canonical_en": "Loyalty Program",
    "category": "payments",
    "definition": "A suite of three automatic discount/reward mechanisms in Zooza: Sibling Discount (discount for families with 2+ children enrolled), Returning Client Discount (discount for clients who re-enrol), and Referral Program (reward for referring new clients). Configured under Sales & Payments → Loyalty Program. Each of the three parts can be enabled or disabled independently.",
    "synonyms": [
      "loyalty programme",
      "loyalty system",
      "rewards programme"
    ],
    "deprecated": [],
    "translations": {
      "sk": "Vernostný program",
      "cz": "Věrnostní program",
      "de": "Treueprogramm",
      "hu": "Hűségprogram",
      "pl": "Program lojalnościowy",
      "ro": "Program de loialitate",
      "it": "Programma fedeltà",
      "fr": "Programme de fidélité"
    },
    "intent_keywords": {
      "en": [
        "loyalty program",
        "loyalty programme",
        "loyalty system",
        "referral",
        "sibling discount",
        "returning client discount",
        "rewards",
        "referral link",
        "referral program",
        "recommendation reward"
      ],
      "sk": [
        "vernostný program",
        "vernostný systém",
        "vernostná zľava",
        "vernostné výhody",
        "referral",
        "odporúcanie",
        "referral link",
        "zľava za súrodenca",
        "vrátenie klienta"
      ],
      "cz": [
        "věrnostní program",
        "věrnostní systém",
        "věrnostní sleva",
        "referral",
        "doporučení",
        "referral link",
        "sourozenecká sleva",
        "sleva pro vracející se klienty"
      ],
      "de": [
        "Treueprogramm",
        "Treuerabatt",
        "Empfehlungsprogramm",
        "Referral",
        "Geschwisterrabatt"
      ],
      "hu": [
        "hűségprogram",
        "ajánlói link",
        "referral",
        "testvérkedvezmény"
      ]
    },
    "ai_notes": "Navigation path: Sales & Payments → Loyalty Program. Three sub-features: 1. Sibling Discount — activated when a second+ child is enrolled under the same account. 2. Returning Client Discount — activated when a client re-books after a previous booking. 3. Referral Program — each client has a unique referral link in their booking widget profile (not in the admin). When a referred client books through the link and completes registration, rewards are issued automatically. The referral link is visible in the booking widget profile section — clients see it whenever they log into the widget on the provider's website. Admins cannot view or copy referral links from the admin panel. IMPORTANT: Referral links are NOT set up manually per client — they exist automatically for every client once the Referral Program is activated. Loyalty discounts from copying registrations (new season) may not apply automatically if the booking history is not inherited by the copy.",
    "do_not_confuse_with": [
      {
        "term": "Discount codes",
        "reason": "Discount codes are single-use or limited-use promo codes entered manually. Loyalty Program discounts are calculated and applied automatically based on booking history, family connections, or referral activity.\n"
      },
      {
        "term": "Retention",
        "reason": "Loyalty Program = rewards active clients (sibling, returning, referral). Retention = re-engages lost clients (Trial Lost / Cancelled).\n"
      }
    ]
  }
];
