// AUTO-GENERATED by scripts/compile-terminology.ts — do not edit by hand.
// Source: src/terminology/terminology.yml
// Run `npm run compile:terminology` to regenerate.

export const TERMINOLOGY_INSTRUCTIONS = `ZOOZA TERMINOLOGY — read before using any tool.

HIERARCHY: Programme → Class → Session → Booking
  Programme = The top-level container that defines an activity type
  Class     = A scheduled group within a Programme, typically differentiated by day/time, leve
  Session   = A single scheduled meeting within a Class, with a specific date and time
  Booking   = A client's formal commitment to attend a Class

TERM RESOLUTION — when a user says X, Zooza means:
  "termín / hodina / lekcia / lekce / óra / lesson" → Session
  "Kurz" (CZ/SK) / "Curs" (RO) / "Kurzus" (HU) → Programme  (NOT deprecated in those markets)
  "skupina / Gruppe" → Class  (not a Programme; Class lives inside a Programme)
  "prihlásenie / prihláška / Buchung" → Booking/Enrolment

DO NOT CONFUSE:
  Class ≠ Programme     (Class lives inside a Programme)
  Session ≠ Class       (Session = one meeting; Class = the recurring schedule)
  Transfer ≠ Copy       (Transfer moves booking; Copy duplicates it)
  Make-up ≠ Free credits  (Make-up = from cancellation; Free credits = granted)`;
